### Numpy Assignment

In [2]:
import numpy as np

1. Create a 3x3 array with random integers between 1 and 100. Write a program to
"normalize" the array so that the values are scaled between 0 and 1.
• Formula: (x - min) / (max - min)
• Example Output: An array where the smallest value becomes 0.0 and the
largest becomes 1.0.

In [5]:

# 1. Create the 3x3 array with random integers between 1 and 100

X = np.random.randint(low=1, high=101, size=(3, 3))
print("Original Matrix X:\n", X)

# this function will perform global min-max normalization on the input matrix
def normalize_global(X):
    # 2. Identify the global min and max scalars
    x_min = X.min()
    x_max = X.max()

    # 3. Calculate the range (denominator)
    # Note: This results in a scalar.
    data_range = x_max - x_min

    # 4. Apply Min-Max Normalization
    normalized_matrix = (X - x_min) / data_range

    return normalized_matrix


X_normalized = normalize_global(X)

print("\nGlobally Normalized Matrix:\n", X_normalized)

# Verification check
print(f"\nMin is now: {X_normalized.min()}")
print(f"Max is now: {X_normalized.max()}")

##########################################

# In Machine Learning, we rarely normalize the entire matrix globally (using one global min/max). Usually, each column represents a different feature (e.g., "Age", "Salary", "Height"). "Age" might range 0-100, while "Salary" ranges 30,000-150,000.
# If we use one global min/max, "Age" would be squashed into a tiny microscopic range because "Salary" is so huge. We need to normalize each column independently.

def normalize_columnwise(X):
    # 1. Identify the column-wise min and max scalars by calculating Min and Max per COLUMN (axis=0)
    col_min = X.min(axis=0)  # shape (3,)
    col_max = X.max(axis=0)  # shape (3,)

    # 2. Calculate the range (denominator) 
    data_range = col_max - col_min  # shape (3,)

    # Handle the case (zero-variance columns) where a column has zero range (max == min) to avoid division by zero
    data_range[data_range == 0] = 1

    # 3. Apply Min-Max Normalization
    normalized_matrix = (X - col_min) / data_range

    return normalized_matrix

X_col_normalized = normalize_columnwise(X)

print("\nColumn-wise Normalized Matrix:\n", X_col_normalized)
# Verification check
print(f"\nColumn-wise Min: {X_col_normalized.min(axis=0)}")
print(f"Column-wise Max: {X_col_normalized.max(axis=0)}")



Original Matrix X:
 [[96 44 99]
 [ 7 62 42]
 [83 98 87]]

Globally Normalized Matrix:
 [[0.9673913  0.40217391 1.        ]
 [0.         0.59782609 0.38043478]
 [0.82608696 0.98913043 0.86956522]]

Min is now: 0.0
Max is now: 1.0

Column-wise Normalized Matrix:
 [[1.         0.         1.        ]
 [0.         0.33333333 0.        ]
 [0.85393258 1.         0.78947368]]

Column-wise Min: [0. 0. 0.]
Column-wise Max: [1. 1. 1.]


2. Create a 1D array of 10 random numbers. Ask the user for a value X Find the value
in the array that is closest to X
• Example Input: Array: [1, 5, 8, 12], X = 10
• Example Output: 8 or 12 (whichever is mathematically closer).

In [ ]:
def find_closest_value(V: np.ndarray, x: float) -> float:
    """
    Finds the value in array V that is mathematically closest to scalar x.
    """

    # Vectorized execution of the mathematical formulation
    # Step A: Distance vector via broadcasting and absolute value
    distances = np.abs(V - x)

    # Step B: Find the index of the minimum distance (the argmin)
    i_star = np.argmin(distances)

    # Step C: Retrieve the closest value
    closest_value = V[i_star]
    return closest_value, i_star

# Create a 1D array of 10 random numbers between 1 and 100
V = np.random.randint(1, 101, size=10)
x = int(input("Enter a target value x : "))
closest_value, i_star = find_closest_value(V, x)
print(f"Array V: {V}")
print(f"Target x: {x}")
print(f"Closest value: {closest_value} (at index {i_star})")

Array V: [46  4 18 58 10  1 84 35  7 73]
Target x: 77
Closest value: 73 (at index 9)


3. Write a NumPy program to create a 5x5 array with random values. For each column
in the array, find the second-largest value.
• Example Input: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
• Example Output: [4, 5, 6] (These are the second-highest values for each
respective column).

In [6]:

# 1. Create a 5x5 matrix with random integers between 0 and 100
A = np.random.randint(0, 100, size=(5, 5))

print("Original Matrix A:")
print(A)

# 2. Partition the array along axis=0 (columns).
# We want the 2nd largest value. In a 0-indexed array of length N, 
# the largest is at -1, so the second largest is at index -2.
# np.partition(A, -2, axis=0) ensures the element at index -2 in each column 
# is exactly the second-largest element.
partitioned_A = np.partition(A, -2, axis=0)

# 3. Extract the row corresponding to the second-largest values
v = partitioned_A[-2, :]

print("\nSecond largest values for each column (v):")
print(v)

Original Matrix A:
[[84 72 53 14 12]
 [59 73 37 84 57]
 [14 49 37 55 30]
 [82 26 19 95 69]
 [23  6 23  7 11]]

Second largest values for each column (v):
[82 72 37 84 57]
